server:
  port: 8888
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhd-smart/smart.git
          searchPaths: config
          username: zhd-smart
          password: 902477zhd.
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/